spring.main.banner-mode: OFF
#logging.pattern.console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%5.5t]){faint} %clr(%logger.%M){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
logging.level.ro.go.adrhc: DEBUG
#logging.org.springframework.context.annotation: ERROR
feign.client.config.default.loggerLevel: BASIC
#logging.file.name: m3u8-playlists-manager.log

metadata-loading-threads: 1c

supported-extensions:
  - jpeg
  - jpg

lucene:
  tokenizer:
    min-token-length: 2
  search:
    max-results-per-search: 25
    result-includes-missing-files: false
  query:
    # tokens to search exactly (aka, without using levenshtein-distance, aka fuzzy)
    # default: lucene.tokenizer.min-token-length + 1
    to-match-exactly-max-token-length: 3
    # minimum words to fuzzy match when fuzzy-words.size > minimum-word-to-match
    # and fuzzy-words.size * part1 / part2 < minimum-word-to-match
    minimum-word-to-match: 2
    # tokens searched using levenshtein-distance
    # minimum-word-to-match formula: part1 / part2
    minimum-word-to-match-part1: 5
    minimum-word-to-match-part2: 6
    # see LevenshteinAutomata.MAXIMUM_SUPPORTED_DISTANCE
    levenshtein-distance: 1
